import Head from "next/head";
import { useId, useState } from "react";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useMutation();
  const [questionInput, setQuestionInput] = useState("");

  function handleClick() {
    hello.mutate({
      text: questionInput,
    });
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black text-white">
        <h1>Hello Agent</h1>
        <Input
          placeholder="Type your question here"
          onChange={(e) => setQuestionInput(e.target.value)}
          className="bg-transparent"
        />
        <Button onClick={handleClick}>Air speed?</Button>
        {hello?.data?.response}
      </main>
    </>
  );
}
